import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {fileURLToPath} from "node:url";
const root=fileURLToPath(new URL("../",import.meta.url));
test("bridge oferece websocket, heartbeat e reconexão compatível",async()=>{const server=await readFile(root+"server.mjs","utf8");assert.match(server,/server\.on\("upgrade"/);assert.match(server,/framePing/);assert.match(server,/\/ws/);});
test("bridge oferece API de comandos e diagnóstico",async()=>{const server=await readFile(root+"server.mjs","utf8");assert.match(server,/\/api\/commands/);assert.match(server,/\/api\/state/);assert.match(server,/\/health/);});
test("redireciona control sem barra e usa recursos absolutos",async()=>{const server=await readFile(root+"server.mjs","utf8");const html=await readFile(root+"public/index.html","utf8");assert.match(server,/pathname==="\/control"/);assert.match(server,/redirect\(response,"\/control\/"\)/);assert.match(html,/href="\/control\/control\.css"/);assert.match(html,/src="\/control\/control\.js"/);});
test("inclui painel profissional de operação",async()=>{const html=await readFile(root+"public/index.html","utf8");assert.match(html,/Cabine de Cobertura/);assert.match(html,/OPERAÇÃO RÁPIDA/);assert.match(html,/REGISTRAR E PUBLICAR/);assert.match(html,/OVERLAYS · PREVIEW/);});

test("oferece a página multicabine real",async()=>{const server=await readFile(root+"server.mjs","utf8");const html=await readFile(root+"public/multicabine.html","utf8");const js=await readFile(root+"public/multicabine.js","utf8");assert.match(server,/\/control\/multicabine\.html/);assert.match(html,/CONTROLE MULTICABINE/);assert.match(js,/clockStartedAt/);});
test("central abre edição da partida pelo identificador",async()=>{const central=await readFile(root+"public/central.js","utf8");const matches=await readFile(root+"public/matches.js","utf8");assert.match(central,/matches\.html\?edit=/);assert.match(matches,/URLSearchParams\(location\.search\)/);});
test("armazenamento preserva listas vazias e relógio por cobertura",async()=>{const store=await readFile(root+"public/data-store.js","utf8");const control=await readFile(root+"public/control.js","utf8");assert.match(store,/if\(!has\(MATCHES_KEY\)\)/);assert.match(control,/clockStartedAt/);assert.doesNotMatch(control,/clockRunning:false}\);\nfunction saveState/);});

test("relógio usa tempo derivado sem incrementar duas fontes",async()=>{const control=await readFile(root+"public/control.js","utf8");assert.match(control,/function effectiveElapsed/);assert.doesNotMatch(control,/state\.elapsedSeconds\+\+/);});
test("nova pauta possui fila própria",async()=>{const store=await readFile(root+"public/data-store.js","utf8");const editorial=await readFile(root+"public/editorial.js","utf8");assert.match(store,/agendas/);assert.match(editorial,/editorial\.agendas/);});
test("partida ativa e saída principal são desserializadas corretamente",async()=>{const store=await readFile(root+"public/data-store.js","utf8");assert.match(store,/const stored = parse\(ACTIVE_MATCH_KEY, ''\)/);assert.match(store,/const stored = parse\(ON_AIR_MATCH_KEY, ''\)/);assert.doesNotMatch(store,/localStorage\.getItem\(ACTIVE_MATCH_KEY\) \|\| ''/);});
test("abertura de cabine propaga matchId e cabine canonicaliza a URL",async()=>{const central=await readFile(root+"public/central.js","utf8");const matches=await readFile(root+"public/matches.js","utf8");const control=await readFile(root+"public/control.js","utf8");assert.match(central,/\/control\/\?matchId=/);assert.match(matches,/\/control\/\?matchId=/);assert.match(control,/history\.replaceState/);assert.match(control,/searchParams\.set\('matchId', match\.id\)/);});
test("diagnóstico do Bridge inicia antes da renderização completa",async()=>{const control=await readFile(root+"public/control.js","utf8");assert.match(control,/if \(!response\.ok\) throw new Error/);assert.match(control,/health\(\);\ntry \{\n  render\(\)/);});

test("multicabine publica imediatamente a partida colocada no ar",async()=>{const js=await readFile(root+"public/multicabine.js","utf8");assert.match(js,/function scoreboardPayload/);assert.match(js,/publishOnAir\(true\)/);assert.match(js,/fetch\('\/api\/commands'/);assert.match(js,/region: 'scoreboard'/);});
test("multicabine mantém o relógio da saída OBS atualizado sem abrir a cabine",async()=>{const js=await readFile(root+"public/multicabine.js","utf8");assert.match(js,/setInterval\(\(\) => \{ render\(\); publishOnAir\(\); \}, 1000\)/);assert.match(js,/signature === lastPublishedSignature/);});
