import test from "node:test";
import assert from "node:assert/strict";
import { Instant } from "@rodrigol/core";
import { EditorialContent,EditorialItem,EditorialPriority,EditorialQueue,EditorialPublisher,DefaultPublicationRule,PublicationChannel,EditorialTemplate,TemplateId,OverlayCommandFactory } from "../dist/index.js";

test("cria, prepara e publica um item editorial",()=>{const item=EditorialItem.create({content:EditorialContent.create({headline:"Gol do Palmeiras"}),priority:EditorialPriority.HIGH,createdAt:Instant.parse("2026-07-27T12:00:00.000Z")});item.markReady();const publications=new EditorialPublisher(new DefaultPublicationRule()).publish(item);assert.equal(item.status,"published");assert.ok(publications.some(p=>p.channel===PublicationChannel.LOWER_THIRD));assert.ok(publications.some(p=>p.channel===PublicationChannel.TICKER));});
test("plantão recebe headline e fullscreen",()=>{const item=EditorialItem.create({content:EditorialContent.create({headline:"Final adiada"}),priority:EditorialPriority.BREAKING});item.markReady();const channels=new DefaultPublicationRule().evaluate(item);assert.ok(channels.includes(PublicationChannel.HEADLINE));assert.ok(channels.includes(PublicationChannel.FULLSCREEN));});
test("fila ordena por prioridade e depois por horário",()=>{const queue=new EditorialQueue();const low=EditorialItem.create({content:EditorialContent.create({headline:"A"}),priority:EditorialPriority.LOW,createdAt:Instant.parse("2026-07-27T10:00:00.000Z")});const high=EditorialItem.create({content:EditorialContent.create({headline:"B"}),priority:EditorialPriority.URGENT,createdAt:Instant.parse("2026-07-27T11:00:00.000Z")});queue.enqueue(low);queue.enqueue(high);assert.equal(queue.next()?.content.headline,"B");});
test("template renderiza conteúdo",()=>{const template=new EditorialTemplate(TemplateId.create(),"Gol","GOL DE {team}!","{player}, aos {minute}");const content=template.render({team:"Flamengo",player:"Pedro",minute:"32 minutos"});assert.equal(content.headline,"GOL DE Flamengo!");assert.equal(content.summary,"Pedro, aos 32 minutos");});
test("não publica rascunho",()=>{const item=EditorialItem.create({content:EditorialContent.create({headline:"Teste"})});assert.throws(()=>new EditorialPublisher(new DefaultPublicationRule()).publish(item));});
test("não duplica publicação no mesmo canal",()=>{const item=EditorialItem.create({content:EditorialContent.create({headline:"Teste"})});item.markReady();item.publish([PublicationChannel.TICKER]);item.publish([PublicationChannel.TICKER]);assert.equal(item.publications.length,1);});
test("publicação gera comando de overlay",()=>{const item=EditorialItem.create({content:EditorialContent.create({headline:"Gol"})});item.markReady();const publication=item.publish([PublicationChannel.LOWER_THIRD],undefined,{headline:"Gol"})[0];const command=OverlayCommandFactory.fromPublication(publication,8000);assert.equal(command.type,"show");assert.equal(command.durationMs,8000);});
